package model;
// Generated 2021�~2��7�� �U��12:30:36 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private int qid;
	private String qname;
	private Set answers = new HashSet(0);

	public Question() {
	}

	public Question(int qid) {
		this.qid = qid;
	}

	public Question(int qid, String qname, Set answers) {
		this.qid = qid;
		this.qname = qname;
		this.answers = answers;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public String getQname() {
		return this.qname;
	}

	public void setQname(String qname) {
		this.qname = qname;
	}

	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

}
